"""
ARIA — Event Stream: Warm Start
=================================
Pre-seeds the simulation state so the first agent cycle sees a system
that is already mid-run rather than starting cold from zero.

What this seeds
---------------
1. Active rider_sessions (shift_end IS NULL) with realistic pre-filled
   earnings/order stats for "hours_already_worked" of sim time.
   Also wires each rider into the Simulator's in-memory state so the
   dispatcher starts assigning orders immediately.

2. rider_health_snapshots — one row per warm rider (real NOW() timestamp)
   so the Earnings Guardian has lag-EPH data for Model 4 trajectory scoring
   on the very first cycle.

3. Redis + simulator.zone_density_cache — loads the latest zone snapshot
   per zone from the DB into Redis (aria:zone_density:{id}) and into the
   Simulator's zone_density_cache dict so pick_delivery_zone gets realistic
   density weights from tick 1.

What this does NOT seed
-----------------------
- restaurant_delay_events / restaurant_delay_hourly — already populated
  by seed_from_v2.py (14 days of baseline data). Restaurant agent scores
  on first cycle without any warm-start help.
- zone_density_snapshots (historical) — already ~120k rows from seed.
- rider_sessions (historical) — already 30 days × 500 riders from seed.
- Any agent output tables (alerts, interventions, briefings, risk_scores)
  — let agents generate fresh. Pre-seeding these would fake results.

Idempotency
-----------
Skipped entirely if open sessions already exist (>10 rows with
shift_end IS NULL), so container restarts do not double-seed.

Called from: services/event-stream/main.py lifespan, after
load_reference_data() and before simulation run().
Controlled by: WARM_START env var (default "true").
"""

import random
import uuid
import structlog
from datetime import datetime, timedelta, timezone

from config import (
    SIMULATION_PEAK_RIDERS,
    SIMULATION_OFFPEAK_RIDERS,
    SUPPLEMENTARY_SHIFT_HOURS,
    DEDICATED_SHIFT_HOURS,
    PEAK_HOURS,
)
from redis_client import key_active_riders, key_rider_state, key_zone_density

log = structlog.get_logger()

# Stable placeholder cycle_id for warm-start health snapshots.
# Real cycle_ids are UUIDs generated by the supervisor per cycle —
# warm-start snapshots use a fixed sentinel so they're identifiable.
_WARM_CYCLE_ID = "00000000-0000-0000-0000-000000000000"

# ── Tuning ──────────────────────────────────────────────────────
# Orders per sim-hour: observed ~2.1 from live session data
# (8.4 avg orders per ~4-6 sim-hr session). Use 0.75 of theoretical
# to account for session start ramp-up and scheduler idle gaps.
_ORDERS_PER_SIM_HOUR = 2.1 * 0.75    # ≈ 1.58

# Avg fare per order — calibrated to actual live data (not theoretical centroid distances).
# Density-weighted zone selection produces ~2km avg delivered distance with ~30% LD rate.
# With BASE_FARE_RS=25: non-LD 2km = 33Rs, LD 6km = 64Rs → weighted avg ≈ 42Rs.
_AVG_FARE_RS         = 42.0

# Fraction of active riders to warm-start (rest come online naturally)
# Keep below 1.0 so the scheduler still sees organic churn/arrival.
_WARM_FRACTION       = 0.85


async def warm_start(clock, db_pool, redis_client, simulator) -> None:
    """
    Entry point. Called once at startup before the simulation loop begins.
    Mutates simulator.active_riders, .rider_current_order, .rider_last_delivery
    and .zone_density_cache directly — that is intentional and safe because
    the simulation loop has not started yet.
    """
    async with db_pool.acquire() as conn:
        open_count = await conn.fetchval(
            "SELECT COUNT(*) FROM rider_sessions WHERE shift_end IS NULL"
        )

    if open_count > 10:
        log.info("warm_start skipped — active sessions already present", open_sessions=open_count)
        return

    sim_now = clock.now()
    is_peak = sim_now.hour in PEAK_HOURS
    target  = SIMULATION_PEAK_RIDERS if is_peak else SIMULATION_OFFPEAK_RIDERS
    n_warm  = max(1, round(target * _WARM_FRACTION))
    pool    = simulator.all_riders

    if not pool:
        log.warning("warm_start skipped — no riders loaded yet")
        return

    candidates = random.sample(pool, min(n_warm, len(pool)))

    sessions_created   = 0
    snapshots_created  = 0

    for rider in candidates:
        rider_id = rider["id"]
        persona  = rider.get("persona_type") or "supplementary"
        target_eph = 90.0 if persona == "supplementary" else 100.0

        shift_range   = DEDICATED_SHIFT_HOURS if persona == "dedicated" else SUPPLEMENTARY_SHIFT_HOURS
        total_shift_h = random.uniform(*shift_range)

        # Rider has been online for 0.5–2.5 sim-hours already
        worked_h      = random.uniform(0.5, min(2.5, total_shift_h - 0.25))
        session_start = sim_now - timedelta(hours=worked_h)
        shift_ends_at = session_start + timedelta(hours=total_shift_h)

        # Skip if the shift would already be over at sim_now
        if shift_ends_at <= sim_now:
            continue

        # Realistic pre-filled stats
        orders_done       = max(0, round(_ORDERS_PER_SIM_HOUR * worked_h * random.uniform(0.8, 1.15)))
        avg_fare          = _AVG_FARE_RS * random.uniform(0.88, 1.12)
        total_earnings    = round(orders_done * avg_fare, 2)
        total_distance_km = round(orders_done * random.uniform(4.5, 7.0), 2)
        long_dist_count   = round(orders_done * random.uniform(0.45, 0.65))
        dead_runs_count   = round(orders_done * random.uniform(0.02, 0.10))
        idle_time_mins    = round(worked_h * 60 * random.uniform(0.08, 0.20), 1)

        session_id = str(uuid.uuid4())
        session_date = session_start.date()

        async with db_pool.acquire() as conn:
            # Clear any closed session for this (rider, date) left by startup cleanup
            # so the INSERT below doesn't hit the UNIQUE (rider_id, session_date) constraint.
            # We never touch open sessions (handled by idempotency check above).
            await conn.execute(
                "DELETE FROM rider_sessions WHERE rider_id=$1 AND session_date=$2 AND shift_end IS NOT NULL",
                rider_id, session_date,
            )

            # Safety: skip if an open session already exists (shouldn't happen but be safe)
            open_session = await conn.fetchval(
                "SELECT id FROM rider_sessions WHERE rider_id=$1 AND session_date=$2 AND shift_end IS NULL",
                rider_id, session_date,
            )
            if open_session:
                continue

            await conn.execute(
                """
                INSERT INTO rider_sessions
                    (id, rider_id, session_date, shift_start,
                     total_orders, total_earnings, total_distance_km,
                     long_distance_count, dead_runs_count, idle_time_mins)
                VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
                """,
                session_id, rider_id, session_date, session_start,
                orders_done, total_earnings, total_distance_km,
                long_dist_count, dead_runs_count, idle_time_mins,
            )
            sessions_created += 1

            # Health snapshot — gives Earnings Guardian lag-EPH for Model 4
            # on the first cycle. Timestamp is real NOW() (matches how the
            # earnings agent writes snapshots: VALUES (..., NOW())).
            if orders_done > 0:
                current_eph   = round(total_earnings / max(worked_h, 1/60), 2)
                projected_eph = round(current_eph * random.uniform(0.92, 1.08), 2)
                below         = current_eph < target_eph
                health_score  = round(min(100.0, (current_eph / target_eph) * 100), 2)

                # cycle_id is NOT NULL — use a stable warm-start placeholder UUID
                await conn.execute(
                    """
                    INSERT INTO rider_health_snapshots
                        (id, rider_id, cycle_id, current_eph, projected_eph,
                         persona_threshold, below_threshold, health_score, timestamp)
                    VALUES ($1, $2::uuid, $3::uuid, $4, $5, $6, $7, $8, NOW())
                    """,
                    str(uuid.uuid4()), rider_id, _WARM_CYCLE_ID,
                    current_eph, projected_eph, target_eph, below, health_score,
                )
                snapshots_created += 1

        # Wire into simulator in-memory state so dispatcher starts immediately
        simulator.active_riders[rider_id] = {
            "rider_id":      rider_id,
            "session_id":    session_id,
            "persona":       persona,
            "home_zone_id":  rider["home_zone_id"],
            "shift_ends_at": shift_ends_at,
        }
        simulator.rider_current_order[rider_id] = None
        simulator.rider_last_delivery[rider_id] = None

        # Redis: mark rider active
        await redis_client.sadd(key_active_riders(), rider_id)
        await redis_client.hset(key_rider_state(rider_id), mapping={
            "session_id":   session_id,
            "home_zone_id": rider["home_zone_id"],
            "status":       "idle",
        })
        await redis_client.expire(key_rider_state(rider_id), 3600)

    # ── Zone density cache ─────────────────────────────────────
    # Load the latest historical snapshot per zone into Redis and into
    # the simulator's zone_density_cache so pick_delivery_zone has
    # density weights and dead-run detection has stress baselines.
    async with db_pool.acquire() as conn:
        snap_rows = await conn.fetch(
            """
            SELECT DISTINCT ON (zone_id)
                zone_id::text,
                density_score,
                stress_ratio,
                order_count,
                active_rider_count,
                order_delta,
                timestamp
            FROM zone_density_snapshots
            ORDER BY zone_id, timestamp DESC
            """
        )

    pipe = redis_client.pipeline()
    for row in snap_rows:
        zid  = row["zone_id"]
        data = {
            "density_score":      str(round(float(row["density_score"] or 0), 4)),
            "stress_ratio":       str(round(float(row["stress_ratio"]  or 0), 4)),
            "order_count":        str(int(row["order_count"]           or 0)),
            "active_rider_count": str(int(row["active_rider_count"]    or 0)),
            "order_delta":        str(int(row["order_delta"]           or 0)),
            "timestamp":          row["timestamp"].isoformat() if row["timestamp"] else sim_now.isoformat(),
        }
        simulator.zone_density_cache[zid] = data
        pipe.hset(key_zone_density(zid), mapping=data)
        pipe.expire(key_zone_density(zid), 900)

    await pipe.execute()

    log.info(
        "warm_start complete",
        riders_activated=sessions_created,
        health_snapshots=snapshots_created,
        zone_cache_entries=len(snap_rows),
        sim_now=sim_now.isoformat(),
    )
