"""
ARIA — MCP Server: FastAPI Application
========================================
Entrypoint. Three things in one process:

  1. MCP protocol layer (fastapi-mcp)
       13 public tools auto-generated from /tools/* routes.
       Claude Desktop connects to /mcp.

  2. Autonomous cycle engine (APScheduler)
       Fires every CYCLE_INTERVAL_MINS.
       Runs all 5 agents → writes DB → broadcasts via WebSocket.

  3. WebSocket server
       GET /ws — frontend + any client connects here.
       Receives cycle briefings (from scheduler) and live events
       (forwarded from Redis pub/sub via ws_manager).

Endpoints:
  GET  /health           — liveness probe (used by docker-compose healthcheck)
  GET  /ws               — WebSocket upgrade
  GET  /tools/*          — 13 MCP tools (auth: X-API-Key)
  POST /cycle/run        — manually trigger a cycle (demo / testing)
  GET  /mcp              — MCP protocol endpoint (auto-generated by fastapi-mcp)
"""

import asyncio
import urllib.request
import json
from contextlib import asynccontextmanager

import httpx
import structlog
import uvicorn
from fastapi import FastAPI, Query, WebSocket, WebSocketDisconnect
from fastapi_mcp import FastApiMCP

from config           import PORT, CYCLE_INTERVAL_MINS, MCP_API_KEY, EVENT_STREAM_HOST
from db               import init_db, close_db, get_pool
from redis_client      import init_redis, close_redis, get_redis
from ws_manager       import ws_manager
from scheduler        import start_scheduler, stop_scheduler, run_cycle, reschedule_cycle
from tools            import router as tools_router
from docs_chat        import router as docs_chat_router, docs_build_index as _build_docs_index
import embedding_client

log = structlog.get_logger()

_redis_bridge_task: asyncio.Task | None = None


# ══════════════════════════════════════════════════════════════
# LIFESPAN
# ══════════════════════════════════════════════════════════════

@asynccontextmanager
async def lifespan(app: FastAPI):
    global _redis_bridge_task

    # ── Startup ───────────────────────────────────────────────
    pool  = await init_db()
    redis = await init_redis()

    # Start Redis → WebSocket bridge as background task
    _redis_bridge_task = asyncio.create_task(ws_manager.start_redis_bridge(redis))

    # Start APScheduler cycle
    start_scheduler(pool, redis, ws_manager)

    # Auto-reschedule to match whatever time_scale the event-stream is currently running at.
    # This survives MCP server restarts without needing the user to re-set time_scale on dashboard.
    try:
        with urllib.request.urlopen(f"{EVENT_STREAM_HOST}/simulation/status", timeout=3) as r:
            status = json.loads(r.read())
            ts = float(status.get("time_scale", 1.0))
            if ts != 1.0:
                reschedule_cycle(ts)
                log.info("auto-rescheduled on startup", time_scale=ts)
    except Exception:
        pass   # event-stream not ready yet — scheduler stays at default 15 min

    # Auto-build PageIndex tree (fast, no LLM calls, rebuilds on every start)
    try:
        result = await _build_docs_index()
        log.info("docs_index_auto_built", total=result["total"])
    except Exception as exc:
        log.warning("docs_index_auto_build_failed", error=str(exc))

    log.info("mcp server started", port=PORT, cycle_interval_mins=CYCLE_INTERVAL_MINS)

    yield

    # ── Shutdown ──────────────────────────────────────────────
    stop_scheduler()
    if _redis_bridge_task:
        _redis_bridge_task.cancel()
        try:
            await _redis_bridge_task
        except asyncio.CancelledError:
            pass
    await close_redis()
    await close_db()
    await embedding_client.close()
    log.info("mcp server stopped")


# ══════════════════════════════════════════════════════════════
# APP
# ══════════════════════════════════════════════════════════════

app = FastAPI(
    title       = "ARIA MCP Server",
    description = "Autonomous Rider Intelligence & Analytics System — MCP + Agent Cycle Engine",
    version     = "1.0.0",
    lifespan    = lifespan,
)

app.include_router(tools_router)
app.include_router(docs_chat_router)


# ══════════════════════════════════════════════════════════════
# HEALTH
# ══════════════════════════════════════════════════════════════

@app.get("/health")
async def health():
    return {"status": "ok"}


# ══════════════════════════════════════════════════════════════
# WEBSOCKET
# ══════════════════════════════════════════════════════════════

@app.websocket("/ws")
async def websocket_endpoint(ws: WebSocket):
    await ws_manager.connect(ws)
    try:
        while True:
            try:
                # Wait for client message; timeout after 15s then send a server ping.
                # This keeps the connection alive through any network/proxy idle timeouts.
                await asyncio.wait_for(ws.receive_text(), timeout=15.0)
            except asyncio.TimeoutError:
                await ws.send_text('{"type":"ping"}')
    except (WebSocketDisconnect, Exception):
        ws_manager.disconnect(ws)


# ══════════════════════════════════════════════════════════════
# MANUAL CYCLE TRIGGER (demo / testing)
# ══════════════════════════════════════════════════════════════

@app.post("/cycle/run")
async def trigger_cycle():
    """
    Manually trigger a full agent cycle outside the 15-min schedule.
    Useful for demos and testing. Returns the cycle briefing synchronously.
    """
    pool  = get_pool()
    redis = get_redis()
    briefing = await run_cycle(pool, redis, ws_manager)
    return briefing


@app.post("/cycle/reschedule")
async def reschedule_cycle_endpoint(time_scale: float = Query(..., gt=0, le=500)):
    """
    Reschedule the agent cycle interval to match the simulation time_scale.
    real_interval = (CYCLE_INTERVAL_MINS * 60) / time_scale  (min 30s).
    Called automatically when the frontend changes the sim time_scale.
    """
    real_secs = reschedule_cycle(time_scale)
    return {"time_scale": time_scale, "real_interval_secs": real_secs}


# ══════════════════════════════════════════════════════════════
# SIMULATION PROXY (keeps event-stream off the public internet)
# ══════════════════════════════════════════════════════════════

@app.get("/simulation/status")
async def simulation_status():
    """
    Proxy: forwards to event-stream /simulation/status.
    Frontend calls this instead of hitting event-stream directly.
    """
    try:
        async with httpx.AsyncClient(timeout=5.0) as client:
            res = await client.get(f"{EVENT_STREAM_HOST}/simulation/status")
        return res.json()
    except Exception:
        return {"error": "event-stream unreachable", "running": False}


@app.post("/simulation/set-timescale")
async def simulation_set_timescale(value: float = Query(..., gt=0, le=500)):
    """
    Proxy: sets event-stream time_scale, then reschedules and triggers
    an immediate agent cycle so the dashboard reflects the new speed.
    """
    pool  = get_pool()
    redis = get_redis()

    # 1. Update sim clock speed
    try:
        async with httpx.AsyncClient(timeout=5.0) as client:
            res  = await client.post(
                f"{EVENT_STREAM_HOST}/simulation/set-timescale?value={value}"
            )
        body = res.json()
    except Exception:
        return {"error": "event-stream unreachable"}

    # 2. Reschedule agent cycle interval
    reschedule_cycle(value)

    # 3. Trigger immediate cycle (fire-and-forget)
    asyncio.create_task(run_cycle(pool, redis, ws_manager))

    return body


# ══════════════════════════════════════════════════════════════
# MCP PROTOCOL LAYER
# ══════════════════════════════════════════════════════════════

mcp = FastApiMCP(
    app,
    name        = "ARIA",
    description = "Autonomous Rider Intelligence & Analytics System — "
                  "zone density, restaurant delay risk, dead run prevention, "
                  "earnings guardian, and cycle briefings.",
)
mcp.mount()


# ══════════════════════════════════════════════════════════════
# ENTRYPOINT
# ══════════════════════════════════════════════════════════════

if __name__ == "__main__":
    # Run as: python main.py (from within services/mcp-server/)
    # PYTHONPATH must include the service root (set in Dockerfile via ENV PYTHONPATH=/app)
    uvicorn.run("main:app", host="0.0.0.0", port=PORT, reload=False)
